### ISSUE TITLE
What is causing this problem?

### ISSUE THREAD

**Issue by Insomnia731** [vanhbakaa/Tapswap#6]
[Tapswap] | 2024-12-18 11:44:32 | INFO     | 89 - Detected 1 sessions | 0 proxies
[Tapswap] | 2024-12-18 11:44:32 | INFO     | 47 - se | Loading user agent from cache...
[Tapswap] | 2024-12-18 11:44:34 | SUCCESS  | 58 - No change in js file: main-11XcHYR9.js
[Tapswap] | 2024-12-18 11:44:35 | INFO     | 345 - se | Processing task 'Work from Home'...
[Tapswap] | 2024-12-18 11:44:38 | ERROR    | 318 - se | Failed to complete items for task 'Work from Home'. Status: 400 | Message: invalid_answer
[Tapswap] | 2024-12-18 11:44:41 | INFO     | 345 - se | Processing task 'Selling Notion Templates'...
[Tapswap] | 2024-12-18 11:44:43 | ERROR    | 318 - se | Failed to complete items for task 'Selling Notion Templates'. Status: 400 | Message: invalid_answer
[Tapswap] | 2024-12-18 11:44:46 | INFO     | 345 - se | Processing task 'Start a Business'...
[Tapswap] | 2024-12-18 11:44:49 | ERROR    | 318 - se | Failed to complete items for task 'Start a Business'. Status: 400 | Message: invalid_answer
[Tapswap] | 2024-12-18 11:44:52 | INFO     | 345 - se | Processing task 'Selling Notion Templates'...
[Tapswap] | 2024-12-18 11:44:54 | ERROR    | 318 - se | Failed to complete items for task 'Selling Notion Templates'. Status: 400 | Message: invalid_answer
[Tapswap] | 2024-12-18 11:44:57 | INFO     | 345 - se | Processing task 'Trading Mistakes'...
[Tapswap] | 2024-12-18 11:44:59 | ERROR    | 318 - se | Failed to complete items for task 'Trading Mistakes'. Status: 400 | Message: invalid_answer

**Comment by vanhbakaa** [comment]
provide correct answer for it in answer.json

**Comment by Insomnia731** [comment]
> provide correct answer for it in answer.json

I used your answer.json which is the default. It has answers. Maybe the problem is in something else.
